/**
 * Establish all Redux actions
 */

const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
const RECEIVE_HOME_DATA = 'RECEIVE_HOME_DATA';
const FETCH_ABOUT_DATA = 'FETCH_ABOUT_DATA';
const RECEIVE_ABOUT_DATA = 'RECEIVE_ABOUT_DATA';

export default {
  FETCH_HOME_DATA,
  RECEIVE_HOME_DATA,
  FETCH_ABOUT_DATA,
  RECEIVE_ABOUT_DATA,
};