/**
 * Establish all Redux actions
 */

export const FETCH_RECIPE_DATA = 'FETCH_HOME_DATA';
export const RECEIVE_RECIPE_DATA = 'RECEIVE_RECIPE_DATA';
export const UPDATE_RECIPE_MODAL_STATUS = 'UPDATE_RECIPE_MODAL_STATUS';
export const UPDATE_RECIPE_DETAIL = 'UPDATE_RECIPE_DETAIL';
export const UPDATE_RECIPE_FAVORITES = 'UPDATE_RECIPE_FAVORITES';
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const UPDATE_SEARCH_ACTIVE_STATUS = 'UPDATE_SEARCH_ACTIVE_STATUS';
